Trtn 41 electrum personal server
bitdeal-nl/theroadtonode pull request #43
Opened 2020-11-29 20:39 UTC by Dirkson643

Stappenplan om Electrum Personal Server te installeren op je Pi

2020-11-30 22:19 UTC, Lexus123 requested changes

2020-11-30 22:19 UTC, Lexus123 commented on bitcoin-core-extensies/electrum-personal-server.md
> +Nu moeten EPS de blockchain van scannen op zoek naar adressen en transacties horend bij de public keys die je in de config-file hebt opgenomen. Als er wordt gevraagd naar de startdatum is het handig
Zin loopt gekkig.

2020-11-30 22:19 UTC, Lexus123 commented on bitcoin-core-extensies/electrum-personal-server.md
> +sudo tail -f -n 200 /home/bitcoin/.bitcoin/bitcoin/debug.log
`/home/bitcoin` user is trouwens niet in lijn met de rest van de tutorial waar `/home/pi` wordt gebruikt. Kan opgelost worden met `~/.bitcoin/blabla`.

2020-11-30 22:19 UTC, Lexus123 commented on bitcoin-core-extensies/electrum-personal-server.md
> +Als deze klaar is start je EPS nog een keer
Mist een puntje.

2020-11-30 22:19 UTC, Lexus123 commented on bitcoin-core-extensies/electrum-personal-server.md
> +sudo systemctl enable eps.service
Commando's in backticks ;)

2020-11-30 22:20 UTC, Lexus123 commented on bitcoin-core-extensies/electrum-personal-server.md
> +nano /home/bitcoin/.bitcoin/bitcoin.conf
`/home/bitcoin` user is trouwens niet in lijn met de rest van de tutorial waar `/home/pi` wordt gebruikt. Kan opgelost worden met `~/.bitcoin/blabla`.

2020-11-30 23:01 UTC, Lexus123 commented
Het bestand `SUMMARY.md` moet ook nog aangepast worden. Of doet Gitbook dat automatisch?

2020-12-01 08:58 UTC, Dirkson643 commented
Feedback verwerkt + summary.md aangepast

2020-12-01 16:33 UTC, Lexus123 approved these changes

2020-12-01 18:40 UTC, merged