Lightning Terminal setup init
bitdeal-nl/theroadtonode pull request #45
Opened 2020-12-01 10:43 UTC by Sebastix

Lightning Terminal setup samen met Loop.
Eventuele stap zou zijn om LiT samen met LND te integreren volgens deze documentatie: https://github.com/lightninglabs/lightning-terminal/blob/master/doc/config-lnd-integrated.md#upgrade-existing-nodes Dat kan handig zijn om ook Faraday en Pool te kunnen gebruiken (deze tools zijn echter nog niet bruikbaar via de LiT UI, maar dat zal een kwestie van tijd zijn)

2020-12-02 09:36 UTC, Lexus123 commented
Ik zie dat hier het NodeJS stukje ook in zit. Geen probleem hoor, maar misschien moeten we na deze PR zulk soort installatie bundelen. NodeJS, Yarn, Golang, whatever nog meer komt... het zijn allemaal zaken die Raspberry Pi breed nodig zijn. Misschien handig om in een latere versie van The Road To Node dit in onderdelen te zetten onder het hoofdstuk "Raspberry Pi"? Dan kunnen onderdelen - zoals LiT, maar ook RTL en LND - verwijzen naar 1 centraal punt.

2020-12-02 09:48 UTC, Sebastix commented
@Lexus123 Daar dacht ik ook al aan, er komt nu veel dezelfde informatie mbt het installeren van deze dependencies. Dit zijn eigenlijk een aantal generieke dependencies die in een aparte categorie geplaatst kunnen worden met installatie instructies.

2020-12-02 13:50 UTC, Lexus123 commented on lightning-extensies/lightning-terminal.md
> +Lightning Terminal automatisch opstarten.
Iets meer verhaaltje van maken :P

2020-12-02 13:50 UTC, Lexus123 commented on lightning-extensies/lightning-terminal.md
> +git clone https://github.com/lightninglabs/loop.git
Betekent dit dat de `loop/` directory in de `/home/pi/lnd` map erbij komt? Ik zie het ook zo in de documentatie van Loop staan, maar is wel weird.

2020-12-02 13:50 UTC, Lexus123 commented on lightning-extensies/lightning-terminal.md
> +Stop LND indien deze actief is.
Als mensen de guide hebben gevolgd, bestaat er ook de kans dat ze LND starten door middel van een systemd service. Dan zal de service automatisch LND proberen te herstarten zodra je hem met `lncli stop` uitzet.

Dan hoef je ook niet meer aan het einde twee terminals open te hebben om te unlocken.

2020-12-02 13:50 UTC, Lexus123 commented on lightning-extensies/lightning-terminal.md
> +Sla de wijzigingen op met Control + X en bevestig met Y.
Backticks om de dingetjes die iemand in moet toetsen ;)

2020-12-02 13:53 UTC, Lexus123 commented
Zie deze [comment](https://github.com/bitdeal-nl/theroadtonode/issues/17#issuecomment-737242859). Als we dus enkel LiT willen hanteren, moet er bij deze PR nog Pool en Faraday bij komen.

2020-12-02 13:55 UTC, Lexus123 commented on lightning-extensies/lightning-terminal.md
> +Stop LND indien deze actief is.
Een korte `sudo systemctl stop lnd` gevolgd door `sudo systemctl start lnd` zou voldoende kunnen zijn.

2020-12-02 14:05 UTC, Sebastix commented on lightning-extensies/lightning-terminal.md
> +git clone https://github.com/lightninglabs/loop.git
Bij mij staat er geen `loop` dir in `/home/sebastix/lnd`. 
Waar zie je dit staan in de documentatie van Loop?

2020-12-02 14:10 UTC, Sebastix commented on lightning-extensies/lightning-terminal.md
> +Stop LND indien deze actief is.
Dit zal ik nog eens goed moeten testen. Voor LND heb ik ook een systemd service ingesteld zoals beschreven in de guide.

2020-12-02 15:09 UTC, Lexus123 commented on lightning-extensies/lightning-terminal.md
> +git clone https://github.com/lightninglabs/loop.git
Haha, sorry! Ik had de `cd ~` over het hoofd gezien! Ik heb niks gezegd 🤐

2020-12-02 15:56 UTC, Sebastix commented on lightning-extensies/lightning-terminal.md
> +git clone https://github.com/lightninglabs/loop.git
Nee, die cd ~ heb ik na je comment nog toegevoegd, dus dat ik denk ik wat je bedoelde. Met die extra stap gaat het zeker goed dat de loop dir in je home dir komt.

2020-12-10 15:27 UTC, Lexus123 commented
Whoops, ik klikte ergens op...

2020-12-10 16:14 UTC, Sebastix commented
Nog niet ready for review ;-) Work in progress / Draft :) Je kunt evt al wel de stappen doorlopen en testen. Gisteren liep ik tegen een Faraday issue aan dat deze niet kon connecten met de lnd rpcserver.

2020-12-13 21:18 UTC, Lexus123 commented on bitcoin-core-extensies/electrum-personal-server.md
> +# Electrum Personal Server
Huh? Waarom staat dit bestand hier? Iets met conflicten of zo?

2020-12-13 21:19 UTC, Lexus123 commented on bitcoin-core-extensies/btc-rpc-explorer.md
> +# BTC RPC Explorer
Huh? Waarom staat dit bestand hier? Iets met conflicten of zo?

2020-12-14 11:30 UTC, Lexus123 commented on android/zap.md
> +# Zap
Hier gaat nog iets mis. Aangezien dit bestand al in master staat en het niet nog een keer toegevoegd kan worden. De PR zou niet moeten aangeven dat dit bestand nieuw is, laat ik het zo zeggen.

2020-12-14 11:31 UTC, Lexus123 commented on android/zap.md
> +# Zap
Oh, er staat ook bij dat dit outdated is of zo

2020-12-14 20:28 UTC, Sebastix commented on android/zap.md
> +# Zap
Ja, dat waren changes die in de develop branch zaten. Als je nu onder de tab Files changed kijkt, zie je maar 3 bestanden die op dit moment anders zijn tov de master branch.

2020-12-15 09:06 UTC, Lexus123 commented
🥳  Ziet er nu goed uit!

Is hij al klaar voor review trouwens? Of waren Pool en Faraday nog WIP?

2020-12-15 14:15 UTC, Sebastix commented
> 🥳 Ziet er nu goed uit!
> 
> Is hij al klaar voor review trouwens? Of waren Pool en Faraday nog WIP?

Nog WIP. Al zou je met deze instructies al wel een heel eind moeten komen om het nodige te installeren. Met Faraday liep ik tegen een rpc connection error aan, dat moet ik nog verder uitzoeken. Daarna wil ik nog de nodige zaken uit deze documentatie opnemen: https://github.com/lightninglabs/lightning-terminal/blob/master/doc/config-lnd-integrated.md#upgrade-existing-nodes zodat je LiT samen met je LND kunt opstarten.

2021-02-27 23:47 UTC, Lexus123 commented
Ik wil LiT ook even oppakken. Vind het best gaaf spul en lijkt mij leuk om hier in te duiken. Het feit dat je vier dingen (LND, Pool, Loop, Faraday) tegelijk kan opstarten, vind ik geniaal! Dan kan de installatie van Lightning weg en vervangen worden met LiT. Het doet immers toch alles.

2021-02-28 18:56 UTC, Sebastix commented
> Ik wil LiT ook even oppakken. Vind het best gaaf spul en lijkt mij leuk om hier in te duiken. Het feit dat je vier dingen (LND, Pool, Loop, Faraday) tegelijk kan opstarten, vind ik geniaal! Dan kan de installatie van Lightning weg en vervangen worden met LiT. Het doet immers toch alles.

Wegens drukte heb ik afgelopen heel weinig aandacht kunnen geven aan Lightning en Bitcoin gerelateerde zaken (op dit moment gaat merendeels van alle updates langs me heen), waaronder ook dus het uitwerken van deze documentatie. Je bent helemaal vrij om ermee te doen wat je wilt :) Als je input van me nodig hebt, wees vrij om dat te vragen dan kijken ik of ik tijd ervoor kan maken :)

2021-03-21 21:55 UTC, Lexus123 requested changes
Alles tot en met pool installatie doorlopen en werkt perfect.

2021-03-21 21:55 UTC, Lexus123 commented on lightning-extensies/lightning-terminal.md
> +faraday --lnd.macaroondir=/home/pi/.lnd/data/chain/bitcoin/mainnet --lnd.tlscertpath=/home/pi/.lnd/tls.cert --lnd.rpcserver=127.0.0.0:10009
Hierna ook weer faraday uitzetten of nieuw venster openen.

2021-03-21 21:55 UTC, Lexus123 commented on lightning-extensies/lightning-terminal.md
> +
Terug naar home

2021-03-31 19:36 UTC, Lexus123 commented on lightning-extensies/lightning-terminal.md
> +#### Yarn
✅ Done

2021-03-31 19:37 UTC, Lexus123 commented on lightning-extensies/lightning-terminal.md
> +Open een tweede terminal scherm om je wallet te unlocken.
✅ Done

2021-04-02 13:53 UTC, Lexus123 commented
Gesloten met v2.1.0

2021-04-02 13:53 UTC, closed without merging